// <auto-generated />
namespace BUDGET.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_code_remove_mooe : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_code_remove_mooe));
        
        string IMigrationMetadata.Id
        {
            get { return "201805270715454_add_code_remove_mooe"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
