// <auto-generated />
namespace BUDGET.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class remove_active : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_active));
        
        string IMigrationMetadata.Id
        {
            get { return "201809240736399_remove_active"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
