// <auto-generated />
namespace BUDGET.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DESC_FUND_SOURCE_HDR : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DESC_FUND_SOURCE_HDR));
        
        string IMigrationMetadata.Id
        {
            get { return "201805210023028_DESC_FUND_SOURCE_HDR"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
