// <auto-generated />
namespace BUDGET.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ORSMOOE_UPDATE : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ORSMOOE_UPDATE));
        
        string IMigrationMetadata.Id
        {
            get { return "201804240027427_ORSMOOE_UPDATE"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
