// <auto-generated />
namespace BUDGET.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ors_head_in_fsh : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ors_head_in_fsh));
        
        string IMigrationMetadata.Id
        {
            get { return "201808160234305_ors_head_in_fsh"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
