// <auto-generated />
namespace BUDGET.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class REMOVE_UNIQUE_EKY : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(REMOVE_UNIQUE_EKY));
        
        string IMigrationMetadata.Id
        {
            get { return "201804300627447_REMOVE_UNIQUE_EKY"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
