// <auto-generated />
namespace BUDGET.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class uacs_sub_codes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(uacs_sub_codes));
        
        string IMigrationMetadata.Id
        {
            get { return "201811160134082_uacs_sub_codes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
