// <auto-generated />
namespace BUDGET.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_dateitme : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_dateitme));
        
        string IMigrationMetadata.Id
        {
            get { return "201807110459418_added_dateitme"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
